### ISSUE TITLE
problem running Orthologs_to_summary.pl 

### ISSUE THREAD

**Issue by hurngyi** [rhysf/Synima#10]
Hi :

   I am using Synima to construct synteny regions between two yeast genomes. However, when I ran perl ../util/Orthologs_to_summary.pl -o all_orthomcl.out. The error message occurred as below. I have no idea what makes this error. BTW, the example in your package works well. Thank you in advance for your help. 

Best

Hurng-Yi Wang

Plotting cluster heatmap...
CMD: R --vanilla -q 1>&2  < ./GENE_CLUSTERS_SUMMARIES.OMCL/write_ortho_heatmap.Rscript
> data = read.table("./GENE_CLUSTERS_SUMMARIES.OMCL/GENE_CLUSTERS_SUMMARIES.cluster_dist_per_genome.txt", com='', sep='\t', skip=1, header=T)
> row.names(data) = paste(data[,1], data[,2])
> data = data[,3:length(data[1,])]
> data_matrix = data.matrix(data)
> postscript("./GENE_CLUSTERS_SUMMARIES.OMCL/GENE_CLUSTERS_SUMMARIES.cluster_dist_per_genome.txt.heatmap.eps")
> par(yaxt='n') # turn off gene labels
> data_heatmap = heatmap(data_matrix, Rowv=NA, scale="none", col=c('black', 'green', 'red'), zlim=c(0,2), margins=c(12,1))
Error in heatmap(data_matrix, Rowv = NA, scale = "none", col = c("black",  : 
  'x' must have at least 2 rows and 2 columns
Execution halted
Error, cmd R --vanilla -q 1>&2  < ./GENE_CLUSTERS_SUMMARIES.OMCL/write_ortho_heatmap.Rscript died with return 256

**Comment by rhysf** [comment]
Dear Hurng-Yi Wang @hurngyi ,

Thanks for your comment. 

I'm not sure of the reason either from the error message. 

Making this heatmap should not be essential for the rest of the pipeline. I would check to see if you have a "GENE_CLUSTERS_SUMMARIES.OMCL/GENE_CLUSTERS_SUMMARIES.clusters" file that has entries in, and if so - you can continue with the pipeline (DAGchainer_from_gene_clusters.pl) without the heatmap.

However, it would be good to try and catch this error regardless. Can you let me know which version of R you are using? I'll probably need you to email me "all_orthomcl.out" as well so I can recreate the error.

Best,
Rhys

**Comment by hurngyi** [comment]
Dear Rhys:

Thank you for the reply. My R version is R version 3.5.1 (2018-07-02), and
attached is the all_orthomcl.out. Thank you again.

Best regards


Hurng-Yi Wang

**Comment by rhysf** [comment]
Thanks. I don't think it is attached. Please email it to rfarrer@broadinstitute.org

**Comment by hurngyi** [comment]
Dear Rhysf/Synima:

    Thank you for your email. I figured out the problem which is due to
identical sequence name generated by previous pipeline (not related to
yours). Many thanks for your attention.

Best regards


Hurng-Yi Wang

**Comment by hurngyi** [comment]
However, I encountered a new problem. After resolving the previous issue, I
am able to conduct the analysis until the final step. After SynIma.pl,
there is an error message. Thank you very much for your help,

Best regards

Hurng-Yi Wang

perl ../SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b
Repo_spec.txt.dagchainer.aligncoords.spans


Running Synima...

Reading /home/hurngyi/Downloads/Synima/yeast/SynIma-output/config.txt...

save_aligncoords_and_reverse_wrapper_from_config...

save_aligncoords_and_reverse_wrapper_from_config: finished

save_aligncoords_spans_and_reverse_wrapper_from_config...

save_aligncoords_spans: saved info for 2 genomes in
/home/hurngyi/Downloads/Synima/yeast/Repo_spec.txt.dagchainer.aligncoords.spans

reverse_placement_on_chromosome_for_genomes_hash...

Problem encountered in find_cumulative_positions for HASH(0x563cb230cc30).
Re-run





Hurng-Yi Wang

**Comment by rhysf** [comment]
Hi @hurngyi 

Glad you figured out that first issue. I have also added a new Note in the README regarding this possible issue, as it is not the first time it has come up. If the issue keeps coming up, i could make the pipeline give unique ids - but would rather not change or add to names for simplicity.

Non-unique IDs may have negatively effected the blast searches, and therefore other steps along the way. My recommendation if you haven't already - is therefore to run a new Synima pipeline from the start with the new unique names you have given - which might solve your issue. If not, please email your aligncoords and aligncoords.spans to rfarrer@broadinstitute.org and I'll try and recreate the issue and find a solution.

Best,
Rhys

**Comment by rhysf** [comment]
@hurngyi found a solution to the issue: A '=' symbol in the contig names was causing the error. I have made the new note in the README about this:

Gene and contig names should also ideally be alphanumerical, and avoid symbols such as '='.
