### ISSUE TITLE
repository sequence databases format issue

### ISSUE THREAD

**Issue by tasbd4** [rhysf/Synima#13]
Hello 

your tool works fine with the examples provided, but when I run on my files it shows format issues. I have annotated the sequences with Prokka. do you suggest other tools for annotation to avoid formatting issues? Suggest me a way, please. I'm new in this field so facing many problems. 

Found 274 mRNA features in ./NC_024124.2/NC_024124.2._callgenes_1.annotation.gff3
Checking FASTA and GFF repository sequence databases match...
fasta_id_to_seq_hash: saving sequences from ./Repo_spec.txt.all.PEP...
gff_to_contig_parent_to_cds_hash: saving all from ./Repo_spec.txt.all.GFF3...

0 / 908 found
./Repo_spec.txt.all.PEP and ./Repo_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match.
fasta_id_to_seq_hash: saving sequences from ./Repo_spec.txt.all.CDS...
gff_to_contig_parent_to_cds_hash: saving all from ./Repo_spec.txt.all.GFF3...

0 / 908 found
./Repo_spec.txt.all.CDS and ./Repo_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match.
Finished.

**Comment by rhysf** [comment]
Hi @tasbd4 

Yes, getting the GFF3, genome and genes to match up is a struggle. I haven't designed Synima with a particular annotation tool in mind. There are some options to select the correct IDs in Create_full_repo_sequence_databases.pl - and it is important it works for the rest of the pipeline to work. Some formats will require editing the IDs in your GFF or FASTA files. If you paste a few lines of your GFF and a couple of IDS in your FASTA files, I might be able to assist further.

Best,
Rhys

**Comment by tasbd4** [comment]
hello @rhysf 
sorry for my late response.

few lines of gff file

##gff-version 3
##sequence-region NC_024124.2 1 169148
NC_024124.2	Prodigal:2.6	CDS	1	2214	.	+	0	ID=NC_024124.2_00001;Parent=NC_024124.2_00001_gene,NC_024124.2_00001_mRNA;Name=rIIA;gene=rIIA;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:UniProtKB:P03690;locus_tag=NC_024124.2_00001;product=Protein rIIA
NC_024124.2	prokka	gene	1	2214	.	+	.	ID=NC_024124.2_00001_gene;Name=rIIA;gene=rIIA;locus_tag=NC_024124.2_00001
NC_024124.2	prokka	mRNA	1	2214	.	+	.	ID=NC_024124.2_00001_mRNA;Name=rIIA;gene=rIIA;locus_tag=NC_024124.2_00001
NC_024124.2	Prodigal:2.6	CDS	2224	3171	.	+	0	ID=NC_024124.2_00002;Parent=NC_024124.2_00002_gene,NC_024124.2_00002_mRNA;inference=ab initio prediction:Prodigal:2.6;locus_tag=NC_024124.2_00002;product=hypothetical protein


FASTA ID

>NC_024124.2
ATGATTATTGAAACGGCTAAAGAAACGATTATTGGTTCAGGCGGGAAGAGCACAGCATTT

**Comment by rhysf** [comment]
Hi @tasbd4

 

Can you also send the top PEP and CDS ID’s.

 

Based on what you have given me so far, if your peptide and cds IDs look like “NC_024124.2_00001_gene”

 

Then the following should work:

 

perl Synima/util/Create_full_repo_sequence_databases.pl -r Repo.txt -f gene

 

If not, can you send the details of those IDs, and the full commands and output of the script?,

Best,

Rhys

**Comment by rhysf** [comment]
as it has now been several months, I assume you overcame the issue or are no longer interested in following this up. If you are, then please open a new issue. Thanks. Rhys
