### ISSUE TITLE
When cloning the git repository I get access rights errors

### ISSUE THREAD

**Issue by Lamm-a** [rhysf/Synima#14]
I just tried to clone the repository using `git clone git@github.com:rhysf/Synima.git ` but get the following error:
```

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
The repositoryd effinatly exists so I assume it is an access rights error. Is this from my end or your end?

**Comment by rhysf** [comment]
Hi @Lamm-a 

Can you try: 

git clone https://github.com/rhysf/Synima.git

instead? That works for me.

**Comment by Lamm-a** [comment]
This works, thank you :)
