### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Lamm-a** [rhysf/Synima#15]
What versioins of the dependencies are requierd and in what capacity must they be installed? Will having them in a conda environment work fine?

**Comment by rhysf** [comment]
I've not gone through to see which versions of prerequisites are required, but you should be set with any recent version listed in the README. Having them in a Conda environment should be fine I think, as long as BLAST for example can be found in PATH.

**Comment by Lamm-a** [comment]
I have done as you suggested and downloaded the current versions of all dependencies listed into a conda environment but get the following error when trying to run the first command:
$ perl ../util/Create_full_repo_sequence_databases.pl -r ./Repo_spec.txt

Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /faststorage/home/lamma/actinobacteria/Synima/util /faststorage/home/lamma/actinobacteria/Synima/util/../modules/ /home/lamma/miniconda3/envs/synima/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/lamma/miniconda3/envs/synima/lib/site_perl/5.26.2 /home/lamma/miniconda3/envs/synima/lib/5.26.2/x86_64-linux-thread-multi /home/lamma/miniconda3/envs/synima/lib/5.26.2 .) at /faststorage/home/lamma/actinobacteria/Synima/util/../modules/read_FASTA.pm line 3.
BEGIN failed--compilation aborted at /faststorage/home/lamma/actinobacteria/Synima/util/../modules/read_FASTA.pm line 3.
Compilation failed in require at /faststorage/home/lamma/actinobacteria/Synima/util/../modules/Synima.pm line 16.
BEGIN failed--compilation aborted at /faststorage/home/lamma/actinobacteria/Synima/util/../modules/Synima.pm line 16.
Compilation failed in require at ../util/Create_full_repo_sequence_databases.pl line 9.
BEGIN failed--compilation aborted at ../util/Create_full_repo_sequence_databases.pl line 9.

**Comment by rhysf** [comment]
Hi @Lamm-a 

The error shows that you have not correctly installed BioPerl. Bio/SeqIO.pm is a core module of BioPerl. You can download this via CPAN for example. In future releases, I may include these modules as part of the repo, but currently, you need to have this installed. Let me know if you have further issues.
