### ISSUE TITLE
Optimizing colors in the figure

### ISSUE THREAD

**Issue by agroppi** [rhysf/Synima#16]
Hi,
First of all, many thanks for your work. I have used Synima on 4 plant genomes.
Here is the figure I have produced (in mode c)
Is there a way to add some differnet colors to make it more clear ?
for example : different color is the position is moving from a chromosome to another
or
only colour the position moving accross chromosomes ?
etc ...
Thanks again

![image](https://user-images.githubusercontent.com/5609985/80372848-748a9d00-8894-11ea-8f6b-fa6bdfb7231b.png)

**Comment by rhysf** [comment]
Dear @agroppi 

Thank you, and glad to see Synima being used to inform orthology and synteny in these plants. The final output (and pipeline in general) could still be improved upon (updates are being considered). Currently some colours can be set from the config file, including the colour of synteny (which defaults to azure4), the colours of individual genes (specified by lists of genes), and specified regions/subsets of synteny (specified by subsets of the aligncoords.spans files (in config or options -t and -u on the command line). There is currently no command line or config option to have alternating chromosome colours, and i'm not sure how exactly this could work if there was large amounts of chromosomal rearrangements between species. However, one solution in your case would be to be extract (using grep for example) certain chromosomes from your aligncoords.spans (such as chr2, 4, 6 and 8) of the bottom genome, and then specify this file as your aligncoords2.spans (-t), with a different colour. I agree that this might look better and clearer than the default.

I have also been finding that touching up the figure in Illustrator or another such program can improve the output further, such as by removing clipping masks that hide the full chromosome name, or bringing chromosome names in front of synteny. You could also edit colours this way too. Future updates will aim to fix such issues automatically.

Best,
Rhys

**Comment by agroppi** [comment]
Dear @rhysf 
Thanks for your detailed answer.
I'll give it a try
