### ISSUE TITLE
Error message in Step 2 of the workflow

### ISSUE THREAD

**Issue by vlb19** [rhysf/Synima#17]
Hi, I keep getting the error message "No genome for ECU07_1410... saved from all_annotations.gff3 (check settings and rerun): Innappropriate ioctl for device"  I think this is because the parameter -num_descriptions is ignored for output formats >4 but when I specify -max_target_seqs the command isn't recognised. Any tips?

**Comment by rhysf** [comment]
Hi @vlb19 

Can you confirm which script is giving this error message? It would also be useful to have your full command, and the full output of the script.

However, I suspect it does not have anything to do with BLAST, and instead is to do with trouble processing the sequences. Can you confirm that you have a genome named ECU07_1410 as a folder, and specified in your repo_spec?

**Comment by vlb19** [comment]
Hi Dr Farrer, 

The script returning this error message is: 
perl ../util/Blast_all_vs_all_repo_to_OrthoMCL.pl -r ./4_genome_spec.txt

The folder is called "Encephalitozoon_cuniculi_GB-M1" which matches the repo_spec document (4_genome_spec.txt). The file saved from all_annotations.gff3 contains many other gene IDs (ECU07_0430-t26_1, ECU09_0650-t26_1, ECU10_0450-t26_1, etc) and I can confirm that ECU05_1170-t26_1 is in the original annotation.cds file. 

Thanks for getting back to me so quickly!

The script runs as follows: 

retrieve_blast_pairs: Printing to OMCL_outdir/all_blast_pairs.m8
Saving ID->Genome from ./4_genome_spec.txt.all.GFF3...
Assigning genome codes...
Vavraia_culicis_floridensis => G001
Encephalitozoon_cuniculi_GB-M1 => G002
Nosema_ceranae_BRL01 => G003
Writing Gcoded version of blast.m8...
Error, no genome for ECU05_1170-t26_1-p1 saved from all_annotations.gff3 (check settings and rerun): Inappropriate ioctl for device

**Comment by vlb19** [comment]
I really appreciate you getting back to me, apologies if this is a simple issue. 
This is the full script output step by step:
$ perl ../util/Create_full_repo_sequence_databases.pl -r ./4_genome_spec.txt
Indexing Vcf...
Indexing EcGBM1...
Indexing NcBRL01...
Creating repository sequence databases...
Copying ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep to ./4_genome_spec.txt.all.PEP...
Copying ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.cds to ./4_genome_spec.txt.all.CDS...
Copying ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep to ./4_genome_spec.txt.all.PEP...
Copying ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.cds to ./4_genome_spec.txt.all.CDS...
Copying ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep to ./4_genome_spec.txt.all.PEP...
Copying ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.cds to ./4_genome_spec.txt.all.CDS...
Combine_all_gff3_files_in_repo: printing to ./4_genome_spec.txt.all.GFF3
trying to remove ID=
EcGBM1: Saving IDs (e.g. ECU07_0430-t26_1). If fail, check settings for matching FASTA and GFFs...
Found 2094 mRNA features in ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.gff3
trying to remove ID=
NcBRL01: Saving IDs (e.g. NCER_102256-t26_1). If fail, check settings for matching FASTA and GFFs...
Found 2615 mRNA features in ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.gff3
trying to remove ID=
Vcf: Saving IDs (e.g. VCUG_01176-t26_1). If fail, check settings for matching FASTA and GFFs...
Found 2774 mRNA features in ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.gff3
Checking FASTA and GFF repository sequence databases match...
fasta_id_to_seq_hash: saving sequences from ./4_genome_spec.txt.all.PEP...
gff_to_contig_parent_to_cds_hash: saving all from ./4_genome_spec.txt.all.GFF3...



0 / 7480 found
./4_genome_spec.txt.all.PEP and ./4_genome_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match.
fasta_id_to_seq_hash: saving sequences from ./4_genome_spec.txt.all.CDS...
gff_to_contig_parent_to_cds_hash: saving all from ./4_genome_spec.txt.all.GFF3...



7480 / 7480 found
./4_genome_spec.txt.all.CDS and ./4_genome_spec.txt.all.GFF3 repository sequence databases are correctly formatted.
Finished.

perl ../util/Blast_grid_all_vs_all.pl -r ./4_genome_spec.txt
fasta_id_to_seq_hash: saving sequences from ./4_genome_spec.txt.all.PEP...
Splitting seq dictionary for blasting...
EcGBM1 = ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP...
Vcf = ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP...
NcBRL01 = ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP...
Using legacy BLAST...
CMD: formatdb -i ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -p T


Building a new DB, current time: 06/02/2020 10:42:47
New DB name:   /mnt/c/Users/vikib/Documents/Work/Imperial_Masters/Comparative_Genomics_Project/Synima/Synima_4_genomes/Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
New DB title:  ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 2773 sequences in 0.0423398 seconds.
CMD: formatdb -i ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -p T


Building a new DB, current time: 06/02/2020 10:42:47
New DB name:   /mnt/c/Users/vikib/Documents/Work/Imperial_Masters/Comparative_Genomics_Project/Synima/Synima_4_genomes/EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
New DB title:  ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 2093 sequences in 0.0325091 seconds.
CMD: formatdb -i ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -p T


Building a new DB, current time: 06/02/2020 10:42:47
New DB name:   /mnt/c/Users/vikib/Documents/Work/Imperial_Masters/Comparative_Genomics_Project/Synima/Synima_4_genomes/NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
New DB title:  ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 2614 sequences in 0.0397692 seconds.
blastall -p blastp -i ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 1000 -b 1000 -e 1e-20 > ./Vcf/RBH_blast_PEP/vs_Vcf.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 5 -b 5 -e 1e-20 > ./Vcf/RBH_blast_PEP/vs_EcGBM1.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 5 -b 5 -e 1e-20 > ./Vcf/RBH_blast_PEP/vs_NcBRL01.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 5 -b 5 -e 1e-20 > ./EcGBM1/RBH_blast_PEP/vs_Vcf.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 1000 -b 1000 -e 1e-20 > ./EcGBM1/RBH_blast_PEP/vs_EcGBM1.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 5 -b 5 -e 1e-20 > ./EcGBM1/RBH_blast_PEP/vs_NcBRL01.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./Vcf/Vcf_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 5 -b 5 -e 1e-20 > ./NcBRL01/RBH_blast_PEP/vs_Vcf.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./EcGBM1/EcGBM1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 5 -b 5 -e 1e-20 > ./NcBRL01/RBH_blast_PEP/vs_EcGBM1.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control outputblastall -p blastp -i ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -d ./NcBRL01/NcBRL01_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -m 8 -v 1000 -b 1000 -e 1e-20 > ./NcBRL01/RBH_blast_PEP/vs_NcBRL01.blast.m8
Warning: [blastp] The parameter -num_descriptions is ignored for output formats > 4 . Use -max_target_seqs to control output

 perl ../util/Blast_all_vs_all_repo_to_OrthoMCL.pl -r ./4_genome_spec.txt
retrieve_blast_pairs: Printing to OMCL_outdir/all_blast_pairs.m8
Saving ID->Genome from ./4_genome_spec.txt.all.GFF3...
Assigning genome codes...
EcGBM1 => G001
Vcf => G002
NcBRL01 => G003
Writing Gcoded version of blast.m8...
Error, no genome for ECU09_0130-t26_1-p1 saved from all_annotations.gff3 (check settings and rerun): Inappropriate ioctl for device

**Comment by rhysf** [comment]
Hi. There is an issue with your very first step:

perl ../util/Create_full_repo_sequence_databases.pl -r ./4_genome_spec.txt

gives the warnings:

0 / 7480 found
./4_genome_spec.txt.all.PEP and ./4_genome_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match.
fasta_id_to_seq_hash: saving sequences from ./4_genome_spec.txt.all.CDS...
gff_to_contig_parent_to_cds_hash: saving all from ./4_genome_spec.txt.all.GFF3...

7480 / 7480 found
./4_genome_spec.txt.all.CDS and ./4_genome_spec.txt.all.GFF3 repository sequence databases are correctly formatted.
Finished.

This indicates that all your CDS files are correctly matching the GFF. However, you PEP files are not. You probably have different ID's for these. If you want to run the rest of the pipeline specifying CDS (parameters for that are included in many of the following steps) you could proceed (I think), but if you want to use PEP sequences - which are likely better for ortholog prediction, then you should rename your PEP the same as your CDS files.

After renaming your PEP files, I recommend deleting all the Synima made files, especially the RBH_output folders for the Blast hits, as Synima will not overwrite these - and it will need to.
