### ISSUE TITLE
Regarding aligncoords_location in the final step

### ISSUE THREAD

**Issue by jeffinrockey** [rhysf/Synima#18]
Hi,

I was trying to run Synima on two mammalian genomes. The steps till the below executed fine using  OrthoMCL towards the later steps.
perl ../SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoords.spans

On execution of the above, the below error came. Would you please advise about this aligncoords_location being indicated and how to define it.
Read_config: aligncoords_location not defined. Check or remake

Thanks & Regards,
Jeffin

**Comment by rhysf** [comment]
Hi @jeffinrockey 

Can you confirm that Repo_spec.txt.dagchainer.aligncoords is in the expected directory (the one you ran the command from: ./Repo_spec.txt.dagchainer.aligncoords).

Also, if you have run the command previously, even unsuccessfully - it may have made the output directory and the config file (./Synima-output/config.txt). If Synima finds this file, even if you have specified the aligncoords on the command line, it will still default to reading and processing the config.txt file - so you will need to either 

a) delete that file
b) specify a new output folder

If that doesn't solve your issue, can you please provide the following:

head Repo_spec.txt.dagchainer.aligncoords
head Repo_spec.txt.dagchainer.aligncoords.spans

and the full output (stdout and stderr) of Synima.pl

**Comment by rhysf** [comment]
I forgot to mention:

c) check the location of aligncoords in config.txt is correct

**Comment by jeffinrockey** [comment]
Dear Dr.Farrer,
  Looks like the second case of unsuccessful execution is what happened. I ran again after deletion and it  executed successfully. Now I just need to work on improving the image as there are  close to 30 chromosomes in each.

Thank you for helping out. Many thanks for Synima. 

I also very much appreciate the example scripts and usages that you provided in the main page. They were very helpful with the initial steps involving gff,pep, clustering etc.
