### ISSUE TITLE
almost empty plot

### ISSUE THREAD

**Issue by aurelim** [rhysf/Synima#20]
Hi, 
I tried to run Synima with my datas and all steps seem to be going well, but at the end i just get a plot with the length of each genome. I add the two dagchainer files in Synima.zip and the plot i get (confif.text.pdf). Do you know what the problem is?
Thank you
Best
aurelie

[config.txt](https://github.com/rhysf/Synima/files/5155678/config.txt)
[config.txt.pdf](https://github.com/rhysf/Synima/files/5155660/config.txt.pdf)
[Synima.zip](https://github.com/rhysf/Synima/files/5155658/Synima.zip)

**Comment by rhysf** [comment]
Hi @aurelim 

There do seem to be some unusual things about the input files. 

Specifically, your aligncoords and aligncoords spans look fine, and they include evidence of syntenic regions in contigs T6SS for both genomes. However, your contig.txt file says the 2 contigs you are plotting are:

contig_order_VAE115.3=VAE115_1210000_1242876_+1
contig_order_VA121223T3.2=VA121223T3_2922143_2950000_+1

Neither of these contig names are T6SS - and they need to match up!

I suspect given the aligncoords and spans files that you are trying to only plot a very small region of the total assembly. Have you already tried the full thing and checked that worked?

Currently, Synima hasn't implemented a way to only show sub-genomic regions. The easiest way would probably be to reduce tour GFF, CDS, PEP and Genome files to that region before running the whole pipeline. Alternatively, you'd probably need to shift all the coordinates (which might be quite tricky, especially factoring in synteny between reverse complimented regions)... 

Currently, Synima was likely trying to add lines between e.g. positions 2923246-2949670 (as specified by your aligncoords.spans), while the FASTA files you've provided are only ~33 kb long. Hence the empty figure.

I suggest making the full plot, perhaps with extra width, and then excluding everything outside of your area of interest.
