### ISSUE TITLE
Further explanation for SynIma.pl options

### ISSUE THREAD

**Issue by javijevi** [rhysf/Synima#21]
Can you provide some further explanation of SynIma.pl options?

For example:

- what is the difference for -k, -l, and -o?

Thanks in advance and best regards,

Javier.

**Comment by rhysf** [comment]
Hi @javijevi 

The README currently explains the config and the overall usage of Synima. In terms of 0k, -l, and -o, the usage and README say:

-k	Gene IDs 1 (1 per line) []
-l	Gene IDs 2 (1 per line) []
-o	Gene IDs 3 (1 per line) []

These parameters are used if you have a file of gene names (1 per line) - which can be cross referenced in you align.coords file (the same IDs are listed in there) - and then these genes will be highlighted in the plot as coloured circles. 

The colours used are R colours, which default to the following in the generated config file:

gene_list_colour1=cornflowerblue
gene_list_colour2=coral3
gene_list_colour3=darkcyan

You can edit the config file and change the colours if required.
Let me know if that covers your questions, or if there were additional parameters you were unclear about.

Best,
Rhys
