### ISSUE TITLE
Reverse complement

### ISSUE THREAD

**Issue by algould** [rhysf/Synima#24]
I'm trying to reverse several chromosomes for a two genome comparison with high syntey (most of the mapped lines within a chr are crossed bt the two genomes). I tried using the "reverse_compliment=" option in the config.txt file, but only the labels in the plot changed (form + to -) - the chromosome position itself doesn't appear to have changed. Is there a way to actually RC the chromosome so that the synteny lines will change too?

**Comment by rhysf** [comment]
Hi @algould 

Can you try plotting gene synteny (g)? 

You can change this in the config file using plot_synteny=g

By default, plot_synteny is set to chromosome/contig synteny (c), which doesn't show orientation.

Best,
Rhys

**Comment by algould** [comment]
This worked great. Thanks for the quick response!
