### ISSUE TITLE
dagchainer entries

### ISSUE THREAD

**Issue by GrantHov** [rhysf/Synima#25]
Hello,

I am trying to visualize synteny data which I generated with my own algorithm.
With my custom data, I tried to build alingcoords and spans files, although there are some columns which meaning I don't understand, and unfortunately DAGchainer's manual does not explain them. And importantly it seems that those values actually affect the final plot. So I was wondering if I can get some help here. In particular, see below an example aligncoords entry:

cpar    5807    cpar:MSTRG.4438.1|4485|u|NA|Contig005807_C_parapsilosis_CDC317|cpar     857369  852885  98      MATCHES ctrop   5       ctrop:MSTRG.7304.1|1366|u|NA|Supercontig_3.5_C_tropicalis_MYA-3404|ctrop        1319492 1320857 142     1e-50   6.0

What are the  columns 6 (i.e 98), 9 (i.e 5), 13 (i.e. 142), and the last two?

Similarly, in the spans entry below:

calb;RA 1993975-1994892 918     ctrop;1 1603853-1604871 1019    -       2       0.90

what are the last two columns and ctrop;1? In the latter case, my guess is that 1 means the chromosome 1, but strangely there is no chromosome named "1" in species.

Thanks in advance

**Comment by rhysf** [comment]
Hi @GrantHov 

You'll have to contact the author of DAGchainer for full details of their output and what each column menas. Synima only makes use of some of these columns, which does not include column 6. 

Here is how Synima processes aligncoords (modules/read_DAG.pm):

my ($genome1, $chr1, $genome1_gene_name, $start1, $stop1, $ignore1, $ignore2, $genome2, $chr2, $genome2_gene_name, $start2, $stop2) = @alignment_info;

so,

cpar = genome1
5807 = chromosome 1
cpar:MSTRG.4438.1|4485|u|NA|Contig005807_C_parapsilosis_CDC317|cpar = genome1 and gene name
857369 = start of gene1
852885 = stop/end of gene 1
98 - ignore 1 (i'm not sure what this is)
MATCHES - ignore2
ctrop - genome2
5 - chromosome2 (chromosome for genome2)
ctrop:MSTRG.7304.1|1366|u|NA|Supercontig_3.5_C_tropicalis_MYA-3404|ctrop = geneome2 and gene name2
1319492 = start (for gene2)
1320857 = stop (for gene2)
142 = i'm not sure
1e-50 = looks like a blast e-value
6.0 = not sure


For aligncoords.spans, its the following:

my ($genome_and_contig1, $ss1, $size1, $genome_and_contig2, $ss2, $size2) = (@bits);

where ss1 and ss2 stand for "start and stop" genomic locations separated by a dash.

Best,
Rhys

**Comment by GrantHov** [comment]
Hi, great thanks, that helped to fix the plot!
