### ISSUE TITLE
how to use synima orthomcl with BLASTn

### ISSUE THREAD

**Issue by GrantHov** [rhysf/Synima#26]
Hi,
Is it possible to use BLASTn instead of legacy blast for performing orthomcl analysis? In other words how can I supply all-to-all blast results to Blast_all_vs_all_repo_to_OrthoMCL.pl?

thanks in advance for help

**Comment by rhysf** [comment]
Hi @GrantHov 

Yes, the script that does the blasts that Blast_all_vs_all_repo_to_OrthoMCL reads in and processes is Blast_grid_all_vs_all.pl. That script checks if you have BLAST+ in your PATH and will use it if you do. If you do not, it will check if you have legacy blast in your PATH and use that if you do. If you have neither, it will call an error. It will also provide a warning as to which BLAST is being used.

Hope that helps,
Rhys

**Comment by GrantHov** [comment]
Hi Rhys,

Thanks for very swift reply and the solution! I managed to run it with BLAST+ (although i had to remove legacy blast because Synima was using it when both software were in the path).
I am now having another related issue. The problem is that I work with very diverged species and in most of the cases there are no significant hits between species, and so blast files are empty, which causes the following error :

Error, no required blast output file: ./calb/RBH_blast_CDS/vs_caur.blast.m8

The file is actually there, but it is empty.
Do you think there is a workaround?
Thanks a lot, your help is appreciated

**Comment by rhysf** [comment]
I can see from the folder name RBH_blast_CDS that you are using CDS/blastn. If you have very diverged species, then PEP/blastp would be more suitable and likely to find some matches. I'd also make sure you are using good gene models, that have a good BUSCO/CEG completeness for example.

**Comment by GrantHov** [comment]
sorry I didn't mention that I am analyzing lncRNAs, which adds complexity since they have very low sequence similarity between species. I was thinking to manually add some hits to the empty files, perform orthomcl and then remove that hits from the final analysis. Can this be a viable solution or it can mess up the analysis?

**Comment by GrantHov** [comment]
ok thanks once again
