### ISSUE TITLE
Using Ensembl Annotation ID to Create repository sequence databases

### ISSUE THREAD

**Issue by ayfchang** [rhysf/Synima#27]
Hello

Your tool works fine with the examples provided, but when I run on my files it shows format issues. 
I have used sequences and gff3 from Ensembl annotations. However, I run into ID format problem with: 

perl ../util/Create_full_repo_sequence_databases_alt.pl -r ./Repo_spec.txt

Indexing mouse...
Indexing nilerat...
Indexing rat...
Creating repository sequence databases...
Copying ./mouse/mouse_ensembl.annotation.pep to ./Repo_spec.txt.all.PEP...
Copying ./mouse/mouse_ensembl.annotation.cds to ./Repo_spec.txt.all.CDS...
Copying ./nilerat/nilerat_ensembl.annotation.pep to ./Repo_spec.txt.all.PEP...
Copying ./nilerat/nilerat_ensembl.annotation.cds to ./Repo_spec.txt.all.CDS...
Copying ./rat/rat_ensembl.annotation.pep to ./Repo_spec.txt.all.PEP...
Copying ./rat/rat_ensembl.annotation.cds to ./Repo_spec.txt.all.CDS...
Combine_all_gff3_files_in_repo: printing to ./Repo_spec.txt.all.GFF3
trying to remove ID=
mouse: Saving IDs (e.g. transcript:ENSMUST00000070533). If fail, check settings for matching FASTA and GFFs...
Found 66516 mRNA features in ./mouse/mouse_ensembl.annotation.gff3
trying to remove ID=
nilerat: Saving IDs (e.g. transcript:ENSANLT00005000003). If fail, check settings for matching FASTA and GFFs...
Found 33508 mRNA features in ./nilerat/nilerat_ensembl.annotation.gff3
trying to remove ID=
rat: Saving IDs (e.g. transcript:ENSRNOT00000072360). If fail, check settings for matching FASTA and GFFs...
Found 29108 mRNA features in ./rat/rat_ensembl.annotation.gff3
Checking FASTA and GFF repository sequence databases match...
fasta_id_to_seq_hash: saving sequences from ./Repo_spec.txt.all.PEP...
gff_to_contig_parent_to_cds_hash: saving all from ./Repo_spec.txt.all.GFF3...

0 / 129129 found
./Repo_spec.txt.all.PEP and ./Repo_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match.
fasta_id_to_seq_hash: saving sequences from ./Repo_spec.txt.all.CDS...
gff_to_contig_parent_to_cds_hash: saving all from ./Repo_spec.txt.all.GFF3...

0 / 129129 found
./Repo_spec.txt.all.CDS and ./Repo_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match.
Finished.

Thanks in advance,

**Comment by rhysf** [comment]
Hi @ayfchang 

It has been expected that the user will parse their input files to correspond to the expected type, with perhaps the use of the available parameters. However, my colleague Dr. David Studholme has kindly shared two of his scripts that he used to convert and Ensembl feature table and the CDS.FASTA to the expected formats. I have put the following scripts in the utility folder, so if you do a fresh clone or pull, then use them as followed:

perl Ensembl_feature_table_to_gff.pl feature_table.txt > Genome.annotation.gff3
perl Ensembl_reformat_fasta.pl cds_from_genomic.fna > Genome.annotation.cds

Hope that helps,
Rhys

**Comment by ayfchang** [comment]
Hi Rhys,

Thank you for your response and uploaded perl scripts. However, upon using them I have the output as empty files.
e.g.
perl Ensembl_feature_table_to_gff.pl mouse_ensembl.annotation.gff > x.gff
perl Ensembl_reformat_fasta.pl mouse_ensembl.annotation.pep > x.pep
perl Ensembl_reformat_fasta.pl mouse_ensembl.annotation.cds > x.cds

x.gff, x.pep, x.cds all appear as empty files.

It there something amiss ?

Best regards,

**Comment by rhysf** [comment]
hi @ayfchang 

I've been informed the names should not have Ensembl at the start, and instead NCBI.

Regardless, the Ensembl/NCBI_feature_table_to_gff.pl should read in an  feature table, not a GFF (e.g. https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/843/895/GCA_003843895.1_ASM384389v1/GCA_003843895.1_ASM384389v1_feature_table.txt.gz)

The Ensembl/NCBI_reformat_fasta.pl is intended for the CDS format (e.g. https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/843/895/GCA_003843895.1_ASM384389v1/GCA_003843895.1_ASM384389v1_cds_from_genomic.fna.gz). 

The peptide file should be fine as is.

If you are unable to figure it out, then please share a few lines of each file and i may be able to suggest something.

Best,
Rhys

**Comment by ayfchang** [comment]
Hi Rhys,

Having looked at your suggestions, I went to NCBI and downloaded the relevant files for my intended species.

I found that for 2 of the species: rat and mouse, the <org>*feature_table.txt does not cover the whole genome.
And the <org>*cds_from_genomic.fna only contains a few sequences. The third species I am interested in has just been
newly sequenced and does not have  <org>*feature_table.txt or <org>*cds_from_genomic.fna.

My original data sources for CDS and PEP and GFF3 were all from Ensembl website, with Ensembl-styled annotations,
they seem to work somehow during repository database (see screen output in original post)

except for places where PEP / CDS processing respectively run to
gff_to_contig_parent_to_cds_hash: saving all from ./Repo_spec.txt.all.GFF3...
0 / 129129 found

I think, "129129  / 129129 found" should be expected if everything turns out OK .

I can still generate a Repo_spec.txt.all.GFF3 (perhaps the output was not right in the last column ?)
e.g.
1       mouse   mRNA    6304503 6345801 .       +       .       transcript:ENSMUST00000161327
1       rat     mRNA    100501676       100506022       .       +       .       transcript:ENSRNOT00000043724
1       nilerat mRNA    1356548 1364520 .       +       .       transcript:ENSANLT00005000004

Thank you for your help so far.

Best regards,

**Comment by rhysf** [comment]
hi @ayfchang 

Thanks, and yes, 129129 / 129129 found should be expected. or at least close to that.

i recommend that you remove the transcript: part of the id in the GFFs, and then ensure that the remaining id's are the first id in the CDS and PEP FASTA files. That should hopefully allow everything to link up correctly. It is possible to do that in a text editor like sublime text, or vim/emacs.  If you are unsure, perhaps there is some local bioinformatics or IT support that you can call on to assist. 

I'll bear in mind the issues you raised, and continue to consider ways that different common formats for IDs in FASTA and GFF files could be automatically identified.

Apologies that i can't be of more use to you on this occasion,
Best,
Rhys

**Comment by ayfchang** [comment]
Hi Rhys,

After re-running from start again with transcript: part of the id in the GFFs removed, I encountered problem after DAGchiainer step. 

I realised my problem is very similar to the previously reported user issue #22 where empty hit_pairs.aligncoords were found whereas there are plenty hit_pairs in dagchainer_rundir. The user in issue #22 was using mammalian species similar to mine. The user was comparing mouse and another mammal, in comparison to me comparing mouse and 2 other rodents.

I saw that issue was closed after you identified the problem arising in the Create_full_repo_sequence_databases stage with ID issues. I though I have cleared that problem here.

I wonder how can I proceed to further de-bug my process ?

Any help will be greatly appreciated.

Thanks !

**Comment by rhysf** [comment]
Their issue was that IDs in their CDS/PEP FASTA file were not in their GFFs. That probably is your issue too.

The output from your Create_full_repo_sequence_databases probably verifies that it is not finding the correct id's. 

Also, the ids in one species should be different from the ids in another species, as described in the README.
