### ISSUE TITLE
Synima GFF3 file issue

### ISSUE THREAD

**Issue by Ivan-Pchelin** [rhysf/Synima#29]
Hello,
Thank you for developing and sharing the project.
Could you please help me to solve the issue with GFF3 files?

I downloaded the GFF3 files from the NCBI Nucleotide database and took care to mention sequence IDs in the GFF3, CDS and PEP files.
The job run as follows:
perl Create_full_repo_sequence_databases.pl -r Repo_spec.txt -f gene
Indexing 113...
Indexing GVESP1...
Indexing EFDG1...
Creating repository sequence databases...
Copying ./113/113.annotation.pep to Repo_spec.txt.all.PEP...
Copying ./113/113.annotation.cds to Repo_spec.txt.all.CDS...
Copying ./GVESP1/GVESP1.annotation.pep to Repo_spec.txt.all.PEP...
Copying ./GVESP1/GVESP1.annotation.cds to Repo_spec.txt.all.CDS...
Copying ./EFDG1/EFDG1.annotation.pep to Repo_spec.txt.all.PEP...
Copying ./EFDG1/EFDG1.annotation.cds to Repo_spec.txt.all.CDS...
Combine_all_gff3_files_in_repo: printing to Repo_spec.txt.all.GFF3
Found no gene features in ./EFDG1/EFDG1.annotation.gff3. Check and re-run

The GFF3 file contained entries like
KP339049.1	EFDG1	CDS	182	319	.	+	0	ID=cds-AXY05368.1;Dbxref=SEED:fig|6666666.327801.peg.1,NCBI_GP:AXY05368.1;Name=AXY05368.1;gbkey=CDS;product=hypothetical protein;protein_id=AXY05368.1;transl_table=11

The CDS file contained entries like
>AXY05368.1_1 [db_xref=SEED:fig|6666666.327801.peg.1] [protein=hypothetical protein] [protein_id=AXY05368.1] [location=182..319] analysisRun=EFDG1 [gbkey=CDS]
ATGACAGATAAAGAAATTTTGGTTTACATGGACTTAGACGAAATTGTAGAATACTACGAAGAAACAGGTC

The PEP file contained entries like
>lcl|KP339049.1_prot_AXY05368.1_1 [db_xref=SEED:fig|6666666.327801.peg.1] [protein=hypothetical protein] [protein_id=AXY05368.1] [location=182..319] analysisRun=EFDG1 [gbkey=CDS]
MTDKEILVYMDLDEIVEYYEETGLADFADSLDIDWTGLLESFGVE

Genomic FASTA started from
>KP339049.1 Enterococcus phage EFDG1, complete genome

Repo_spec.txt mentioned
//
Genome EFDG1
Annotation EFDG1
//

**Comment by rhysf** [comment]
Hi @Ivan-Pchelin 

Because you are using -f gene, it is looking for gene features in your GFF3, while I can see from the entry you showed, that is a CDS feature (3rd column). 

If you want to use those CDS features in your GFF to map onto the 2 FASTA, then you will need to replace CDS with gene in your GFF.

By default, Create_sequence_dictionary removed 'ID=' from GFF's, which can be changed with -m.
However, the script will then be looking to match up genes in the GFF with the id e.g. cds-AXY05368.1

to FASTA IDs:

AXY05368.1_1 [db_xref=SEED:fig|6666666.327801.peg.1] [protein=hypothetical protein] [protein_id=AXY05368.1] [location=182..319] analysisRun=EFDG1 [gbkey=CDS]
and
lcl|KP339049.1_prot_AXY05368.1_1 [db_xref=SEED:fig|6666666.327801.peg.1] [protein=hypothetical protein] [protein_id=AXY05368.1] [location=182..319] analysisRun=EFDG1 [gbkey=CDS]

which are not cds-AXY05368.1. 

You will therefore have to rename the IDs in those FASTA files accordingly.



Rhys

**Comment by rhysf** [comment]
For the command you are using, the following lines should match:

GFF:

KP339049.1 EFDG1 gene 182 319 . + 0 ID=cds-AXY05368.1;Dbxref=SEED:fig|6666666.327801.peg.1,NCBI_GP:AXY05368.1;Name=AXY05368.1;gbkey=CDS;product=hypothetical protein;protein_id=AXY05368.1;transl_table=11

CDS FASTA:

>cds-AXY05368.1

PEP FASTA:

>cds-AXY05368.1

**Comment by Ivan-Pchelin** [comment]
@rhysf 
Thank you for your reply. I edited the GFF3 files obtained from NCBI in Excel by importing with TAB and semicolon delimiters, editing second and third columns and copying back into GFF3 (plain text) files. I came through all the steps described in Full example pipeline at https://githubmemory.com/repo/rhysf/Synima, but the resulting PDF file makes no sense. Currently trying to find out what caused it.

**Comment by Ivan-Pchelin** [comment]
@rhysf 
Thank you for your reply. I edited the GFF3 files obtained from NCBI in Excel by importing with TAB and semicolon delimiters, deleting all lines except for those containing peptide annotations, editing second and third columns and copying back into GFF3 (plain text) files. I went through all the steps described in Full example pipeline at https://githubmemory.com/repo/rhysf/Synima, but the resulting PDF file makes no sense. Do you have any ideas? I attached the figures
[Picture1.pdf](https://github.com/rhysf/Synima/files/7538847/Picture1.pdf)
[Picture2.pdf](https://github.com/rhysf/Synima/files/7538848/Picture2.pdf)
.

**Comment by Ivan-Pchelin** [comment]
@rhysf 
Here are my working fil
[Schiekvirus.zip](https://github.com/rhysf/Synima/files/7538984/Schiekvirus.zip)
es

**Comment by rhysf** [comment]
That doesn't look right. I can look into this but i will not more information and probably files:

Can you send me a complete list of all commands you used to generate those figures, including the warnings and outputs of each script. I will also need the Synima files it generated and the aligncoords files?

**Comment by Ivan-Pchelin** [comment]
I created the graphs using
perl ../util/Create_full_repo_sequence_databases.pl -r Repo_spec.txt -f gene
perl ../util/Blast_grid_all_vs_all.pl -r Repo_spec.txt -e 0.001
perl  ../util/Blast_all_vs_all_repo_to_OrthoMCL.pl -r Repo_spec.txt
perl ../util/Orthologs_to_summary.pl -o all_orthomcl.out
perl ../util/DAGchainer_from_gene_clusters.pl -r Repo_spec.txt -c GENE_CLUSTERS_SUMMARIES.OMCL/GENE_CLUSTERS_SUMMARIES.clusters
perl ../SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoords.spans
[Schiekvirus.zip](https://github.com/rhysf/Synima/files/7539351/Schiekvirus.zip)

**Comment by rhysf** [comment]
[SynIma-files-and-output.zip](https://github.com/rhysf/Synima/files/7540405/SynIma-files-and-output.zip)

Hi @Ivan-Pchelin 

When i tried to run your final Synima command, it failed on the following error:

genome_contig_lengths_GVESP1=>MZ333462.1 not found in config. Remake or edit /Users/rhysfarrer/Downloads/Schiekvirus/SynIma-output/config.txt


I'm not sure how this has happened (do you have any ideas?), but your aligncoords and aligncoords had for 

genome GVESP1
contig MZ333462.1

the contig listed as: >MZ333462.1, which does not match the rest of your files.

When i removed that '>' symbol from both files, it ran correctly.
I also took the liberty of running with -g g to see where genes are... All looks fine now (see attached input and output files).

Best,
Rhys

**Comment by Ivan-Pchelin** [comment]
Hi @rhysf,
Thank you so much for your support. I introduced those angle brackets at some moment and forgot about it. For now, I managed to visualize the entire dataset. Thank you again.
