### ISSUE TITLE
non mRNA/gene features

### ISSUE THREAD

**Issue by sejmodha** [rhysf/Synima#3]
Hi There,

I was wondering if it is possible to include other features such as pseudogenes in the Synima analysis?

Thanks

**Comment by rhysf** [comment]
Hi @sejmodha ,

Providing you get those features into the required aligncoords and aligncoords.spans format - then it will work.

If using the Synima pipeline for ortholog prediction, then the feature you are interested in can be specified by the -f (feature) parameter of the first step of the ortholog prediction pipeline Create_full_repo_sequence_databases.pl

However, I think the feature will require a peptide and nucleotide sequence in the respective FASTA files to work. 

One work around might be to create a pseudo peptide sequence (with the same IDs as the CDS FASTA) if one does not exist - and then make sure only CDS is used as parameters for the following ortholog prediction steps.

Hope that is useful.
Rhys
