### ISSUE TITLE
Error on OrthoMCL execution on BLAST output

### ISSUE THREAD

**Issue by immanuelazn** [rhysf/Synima#30]
Hi,
I am encountering an issue with both the example, and my own data set for synima, and I was wondering if I could get some insight.  I was able to use prokka to create genome annotations between two closely related species, and put it through the synima example pipeline using the following commands:
`perl ../util/Create_full_repo_sequence_databases.pl -r ./Repo_spec.txt -t CDS '

'perl ../util/Blast_grid_all_vs_all.pl -r ./Repo_spec.txt`

However, I am having an issue with the next step of the pipeline.  Using RBH, Orthofinder, and OrthoMCL, I am encountering an issue that I am not sure how to solve.  I noticed that I encounter the same issue when working with the example dataset given.  

Can't exec "/home/.../Synima/util/support_scripts/Blast_m8_to_OrthoMCL_gg_and_bpo_input.pl": Permission denied at /home/.../Synima/util/../modules/Synima.pm line 405.
Error, cmd /home/.../Synima/util/support_scripts/Blast_m8_to_OrthoMCL_gg_and_bpo_input.pl OMCL_outdir/for_omcl.Gcoded.m8 4 OMCL_outdir/omcl_in died with return -1

I tried to look under the files giving the errors, and I wasn't really having any success.  Any idea how I can continue down the pipeline?

Thanks!

**Comment by rhysf** [comment]
Hi @immanuelazn 

Can you post all the warnings that the script outputted?

Thanks,
Rhys

**Comment by immanuelazn** [comment]
Hi @rhysf,

I believe those _are_ all the warnings that are being outputted.
I have attached the entire output of running that line here:


>perl ../util/Blast_all_vs_all_repo_to_OrthoMCL.pl -r ./Repo_spec.txt
retrieve_blast_pairs: Printing to OMCL_outdir/all_blast_pairs.m8
Saving ID->Genome from ./Repo_spec.txt.all.GFF3...
Assigning genome codes...
Cryp_gatt_CA1280_V1 => G001
CNB2 => G002
Writing Gcoded version of blast.m8...
CMD: sort -T . -S 2G -k1,1 -k12,12gr OMCL_outdir/for_omcl.Gcoded.m8.tmp > OMCL_outdir/for_omcl.Gcoded.m8
Done
See file: OMCL_outdir/for_omcl.Gcoded.m8
CMD: perl ../data/Synima/util/support_scripts/Blast_m8_to_OrthoMCL_gg_and_bpo_input.pl OMCL_outdir/for_omcl.Gcoded.m8 4 OMCL_outdir/omcl_in
Done.  See 67.gg and 67.bpo
>
>CMD: perl ../data/Synima/util/support_scripts/OrthoMCL.pl --mode 4 --bpo_file OMCL_outdir/omcl_in.bpo --gg_file OMCL_outdir/omcl_in.gg 2>&1 | tee OMCL_outdir/omcl.log
Using Linux : ../data/Synima/util/support_scripts/mcl.Linux
> ### WORKING DIRECTORY: ###
>  ./Mar_7/
>
>
>There are 2 genomes, 13093 sequences in OMCL_outdir/omcl_in.gg !
>
>
>Identifying inparalogs from G002
241 sequences have better hits within species
150 sequence pairs were identified as Reciprocal Better/Best Hit
>
>Identifying inparalogs from G001
299 sequences have better hits within species
203 sequence pairs were identified as Reciprocal Better/Best Hit
>
>Identifying ortholog pairs between G002 and G001
12136 sequences have best hits from the other species
6215 sequence pairs were identified as Reciprocal Better/Best Hit
Appending co-ortholog pairs between G002 and G001: 59 pairs
G002 and G001 average weight: 259.203805364931
>
>calculate average weight from G002
G002 average weight: 311.714416666667
>
>calculate average weight from G001
G001 average weight: 310.167252941177
>
>There are 11905 sequences to cluster
Matrix(11905 X 11905) file ./Mar_7/tmp/all_ortho.mtx generated
>
>Index file ./Mar_7/tmp/all_ortho.idx generated
>
>Run MCL program
  ../data/Synima/util/support_scripts/mcl.Linux ./Mar_7/tmp/all_ortho.mtx -I 1.5 -o ./Mar_7/tmp/all_ortho.mcl
Can't exec "../data/Synima/util/support_scripts/mcl.Linux": Permission denied at ../data/Synima/util/support_scripts/../../modules/orthomcl_module.pm line 481, <BPOFILE> line 122500.
>
>
>../data/Synima/util/support_scripts/OrthoMCL.pl:
Unexpected error (should not have happened):
./Mar_7/tmp/all_ortho.mcl failed to be generated!
No such file or directory
>
>Error, cannot extract final result filename from OMCL_outdir/omcl.log at ../util/Blast_all_vs_all_repo_to_OrthoMCL.pl line 58.

**Comment by rhysf** [comment]
Hi. The permission of mcl.Linux is set to executable, so i'm not sure what could be the issue: 

-rwxrwxr-x  1 staff    823564  2 Oct  2019 mcl.Linux*

I suggest navigating to that folder, and trying to run it, and perhaps try changing the permission manually with chmod. You could also inquire with whoever manages your Linux server if there should be a problem from running that command in terms of permissions. You can also consider using the RBH or Orthofinder alternatives which I think should bypass requiring MCL.

**Comment by rhysf** [comment]
I assume this issue has been resolved now as it has been a few months.
