### ISSUE TITLE
setp for running Synima.pl 

### ISSUE THREAD

**Issue by Niohuruzh** [rhysf/Synima#34]
Hello, synima team
  I have encounter a problem when I run` perl ../SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoord.spans`. The process is showed as followed:

> Running Synima...
> making output directory ../SynIma-output...
> Saving genome names from Repo_spec.txt.dagchainer.aligncoords.spans...
> fasta_to_total_seq_length: saving sequences from CNB2/CNB2.genome.fa...
> fasta_id_to_seq_length_hash: saving sequences from CNB2/CNB2.genome.fa...
> fasta_id_to_order_array: saving order from CNB2/CNB2.genome.fa...
> fasta_to_total_seq_length: saving sequences from Cryp_gatt_CA1280_V1/Cryp_gatt_CA1280_V1.genome.fa...
> fasta_id_to_seq_length_hash: saving sequences from Cryp_gatt_CA1280_V1/Cryp_gatt_CA1280_V1.genome.fa...
> fasta_id_to_order_array: saving order from Cryp_gatt_CA1280_V1/Cryp_gatt_CA1280_V1.genome.fa...
> fasta_to_total_seq_length: saving sequences from CNB_WM276_v2/CNB_WM276_v2.genome.fa...
> fasta_id_to_seq_length_hash: saving sequences from CNB_WM276_v2/CNB_WM276_v2.genome.fa...
> fasta_id_to_order_array: saving order from CNB_WM276_v2/CNB_WM276_v2.genome.fa...
> fasta_to_total_seq_length: saving sequences from Cryp_gatt_IND107_V2/Cryp_gatt_IND107_V2.genome.fa...
> fasta_id_to_seq_length_hash: saving sequences from Cryp_gatt_IND107_V2/Cryp_gatt_IND107_V2.genome.fa...
> fasta_id_to_order_array: saving order from Cryp_gatt_IND107_V2/Cryp_gatt_IND107_V2.genome.fa...
> Making config file ../SynIma-output/config.txt...
> Reading ../SynIma-output/config.txt...
> save_aligncoords_and_reverse_wrapper_from_config...
> save_aligncoords_and_reverse_wrapper_from_config: finished
> save_aligncoords_spans_and_reverse_wrapper_from_config...
> save_aligncoords_spans: saved info for 4 genomes in ../Repo_spec.txt.dagchainer.aligncoords.spans
> reverse_placement_on_chromosome_for_genomes_hash...
> /home/lei/miniconda3/envs/r/lib/R/bin/exec/R: /home/leigod/miniconda3/envs/r/lib/R/bin/exec/../../lib/../../libtinfo.so.6: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)
> [1] "SynIma: Generating pdf. May take some time..."
> null device 
>           1 

 However, the `.pdf` file is generated. I dont understand quitely whether the `null device` in the last line is an error signal?

Looking forward your reply
Best regards!

**Comment by rhysf** [comment]
Hi @Niohuruzh 

I believe the 'null device' is the standard warning message from R after completing writing to a particular source (dev.off()) - so can be ignored.

**Comment by Niohuruzh** [comment]
> 
Thats great. Thanks for your reply!
