### ISSUE TITLE
Highlight supercontigs on plot

### ISSUE THREAD

**Issue by lilypeck** [rhysf/Synima#40]
Hello

Thanks for this great tool! 

I have created my synteny plot. I'd like to highlight certain supercontigs of interest, but I can't get the -t function to work

I have created a .txt file by grepping the aligncoords.span e.g.
```
head chr1.matches.txt 
Fol;NC_030986.1	799703-1728812	929110	Robusta254;c1	467651-1522619	1054969	+	253	0.88
Coffea659;c1	720625-1600171	879547	Fol;NC_030986.1	948357-1728812	780456	+	219	1.13
Fol;NC_030986.1	685349-1399130	713782	Fver;NC_031675.1	639169-1389515	750347	+	201	0.95
Arabica563;c1	6318477-7003102	684626	Fol;NC_030986.1	5006185-5517220	511036	+	174	1.34
Fol;NC_030986.1	2599597-3025094	425498	Fver;NC_031675.1	2598633-3018871	420239	+	129	1.01
Fol;NC_030986.1	4950077-5344497	394421	Fver;NC_031675.1	4934640-5328802	394163	+	129	1.00
Arabica563;c1	1202774-1696652	493879	Fol;NC_030986.1	1329510-1728812	399303	+	118	1.24
Fol;NC_030986.1	1906600-2271537	364938	Fver;NC_031675.1	1906404-2275570	369167	+	113	0.99
Coffea659;c1	5257542-5682266	424725	Fol;NC_030986.1	4883092-5239165	356074	+	110	1.19
Coffea659;c1	4831116-5241179	410064	Fol;NC_030986.1	4509775-4871332	361558	+	104	1.13
```

And I am running the below - 
```
perl Synima/SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoords.spans -t chr1.matches.txt 
Running Synima...
Reading /rds/general/user/ldp18/home/synima/SynIma-output/config.txt...
save_aligncoords_and_reverse_wrapper_from_config...
save_aligncoords_and_reverse_wrapper_from_config: finished
save_aligncoords_spans_and_reverse_wrapper_from_config...
save_aligncoords_spans: saved info for 10 genomes in /rds/general/user/ldp18/home/synima/Repo_spec.txt.dagchainer.aligncoords.spans
reverse_placement_on_chromosome_for_genomes_hash...
[1] "SynIma: Generating pdf. May take some time..."
null device 
          1 
(synima) [ldp18@login-a synima]$ Rscript SynIma-output/config.txt.Rscript 
[1] "SynIma: Generating pdf. May take some time..."
null device 
          1 
```

My questions are: 
1. As you can see from the attached plot, none of the synteny regions are shaded in a different colour? How do I tell it to use the alternate colours listed in my config.txt file?
2. How do I highlight the location of all genes using small black boxes (as in your 2017 BMC Bioinformatics paper)? 

Thanks in advance

Lily

[config.txt.highlighted.pdf](https://github.com/rhysf/Synima/files/10674593/config.txt.highlighted.pdf)

**Comment by rhysf** [comment]
Dear Lily,

Great! Thanks for sharing.

The reason -t is probably not working, is that you have run Synima once, generating a config file - which synima is now reading, and ignoring further command line parameters. The solution is to either 

1) specify a new config file/output on the command line
2) edit the config file for the file instead

Personally, i would opt for option 2, so you can make additional changes to the figure, and improve upon it. One suggestion is that contig "NC_030987.1" in Fol probably shouldn't be reversed for example - so it will match up more clearly with the other contigs.

Hope that's useful, but let me know if you have further questions.

**Comment by lilypeck** [comment]
Dear Rhys

Thanks for your quick reply! 

Option 2 sounds good, I have already edited the config file anyway by removing some genomes from the plot and re-ordering the remainder. 

I cannot see anywhere in the manual what I add into the config file (attached) to highlight (1) certain contigs and (2) all gene locations with black boxes? It would be great if you could signpost this for me please!

Thanks again

Lily 

[config.txt](https://github.com/rhysf/Synima/files/10676116/config.txt)

**Comment by rhysf** [comment]
Hi Lily,

if you want to include (up to 3) subsets of the aligncoords spans files, then you could add the following line(s):

aligncoords_spans_location1=/location/of/file
aligncoords_spans_location2=/location/of/file
aligncoords_spans_location3=/location/of/file

in terms of choosing colours, those can be changed with these:

aligncoords_spans_colour1=azure4
aligncoords_spans_colour2=red
aligncoords_spans_colour3=blue


In terms of "all gene locations with black boxes", that is specified by:

plot_individual_genes=y

or

plot_individual_genes=n


If you wanted to highlight specific genes, you can make a file listing their ID's (matching the ID's given in the aligncoords file), with:

gene_list1=/location/of/file
gene_list2=/location/of/file
gene_list3=/location/of/file

and the colours:

gene_list_colour1=cornflowerblue
gene_list_colour2=coral3
gene_list_colour3=darkcyan


Hope that helps.

**Comment by lilypeck** [comment]
Hi Rhys, 

Thanks a million, it is so simple, what a great tool! 

Lily

ps Mat Fisher recommended I make a synima plot following my phd viva, very glad I have done

![config 16](https://user-images.githubusercontent.com/108482651/218145036-d90bc35e-0f0f-4a75-8967-6e3b904a458d.jpg)

**Comment by rhysf** [comment]
Thanks Lily - glad it's gone well and appreciate that!

BTW - you might be able to manually make your plot a little clearer. 

For example if you reverse compliment NC_030987.1 AND c2 - that will avoid those 2 reversals. 
You might also do a better job of ordering than what is currently implemented by Synima

Finally, in terms of taxa ordering - you might find the synteny plot more meaningful if ordered by a phylogenetic tree (if that hasn't already been done)

Thanks again!
