### ISSUE TITLE
aligncoords files empty

### ISSUE THREAD

**Issue by anacmj24** [rhysf/Synima#41]
Hello,

I am running Synima, and all the steps described in your main protocol seems to be generating outputs except the last one. After giving the last command to run Synima, I get the following message: 

`perl ../SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoords.spans
Running Synima...
making output directory /Applications/Synima/syntheny_chom/SynIma-output...
Saving genome names from Repo_spec.txt.dagchainer.aligncoords.spans...
Nothing saved from Repo_spec.txt.dagchainer.aligncoords.spans. Check file and that is confirms to save_aligncoords.spans format.`

I can see that de "dagchainer_rundir" has four files (dagchainer.cmds, lcup_vs_mychom.dagchainer.conf, lcup_vs_mychom.hit_pairs, cup_vs_mychom.hit_pairs.aligncoords), and only the .aligncoords is empty. Likewise, the files Repo_spec.txt.dagchainer.aligncoords and Repo_spec.txt.dagchainer.aligncoords.spans in the main folder are also empty. 

Would you have any ideas of what could be happening?

Below I send you the set of commands used:

`perl ../util/Create_full_repo_sequence_databases.pl -r ./Repo_spec.txt`

`perl ../util/Blast_grid_all_vs_all.pl -r ./Repo_spec.txt`

`perl ../util/Blast_all_vs_all_repo_to_RBH.pl -r ./Repo_spec.txt`

`perl ../util/Orthologs_to_summary.pl -o ./RBH_outdir/PEP.RBH.OrthoClusters -t RBH -d RBH_outdir`

`perl ../util/DAGchainer_from_gene_clusters.pl -r ./Repo_spec.txt -c GENE_CLUSTERS_SUMMARIES.RBH/GENE_CLUSTERS_SUMMARIES.clusters`

`perl ../SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoords.spans`

Thank you in advance for your help!

**Comment by rhysf** [comment]
Hi @anacmj24 

I would need to see all the warning messages you got with each command as well. The issue is often the first step, so if you try and run that again (you'll have to delete the files it produces first) - that will reveal that as the issue, or rule it out.

Other files that have zero size will also be a good indication of the issue.

**Comment by anacmj24** [comment]
Hi @rhysf 

Thank you for your quick reply. After deleting all outputs, I rerun the first command, and indeed there are warnings messages regarding the matching format of the files .gff3 and .fasta. I have downloaded one of the genomes from genbank, so I am not sure how to fix the matching format. If you have any insight, it will be welcomed! Thanks again...

The log is below:

`perl ../util/Create_full_repo_sequence_databases.pl -r ./Repo_spec.txt
combine_all_gff3_files_in_repo: printing to ./Repo_spec.txt.all.GFF3
combine_all_gff3_files_in_repo: opening ./mychom/mychom.annotation.gff3
combine_all_gff3_files_in_repo: removing ID= from IDs for mychom...
combine_all_gff3_files_in_repo: saving IDs (e.g. maker-scaffold191|size626036-augustus-gene-0.0-mRNA-1) for mychom...
combine_all_gff3_files_in_repo: found 15408 mRNA features in ./mychom/mychom.annotation.gff3
combine_all_gff3_files_in_repo: opening ./lcup/lcup.annotation.gff3
combine_all_gff3_files_in_repo: removing ID= from IDs for lcup...
combine_all_gff3_files_in_repo: saving IDs (e.g. rna-XM_046954696.1) for lcup...
combine_all_gff3_files_in_repo: found 22082 mRNA features in ./lcup/lcup.annotation.gff3
Indexing mychom...
Indexing lcup...
Creating repository sequence databases...
Copying ./mychom/mychom.annotation.pep to ./Repo_spec.txt.all.PEP for mychom...
Copying ./mychom/mychom.annotation.cds to ./Repo_spec.txt.all.CDS for mychom...
Copying ./lcup/lcup.annotation.pep to ./Repo_spec.txt.all.PEP for lcup...
Copying ./lcup/lcup.annotation.cds to ./Repo_spec.txt.all.CDS for lcup...
Checking FASTA and GFF repository sequence databases match...
fasta_to_struct: saving from ./Repo_spec.txt.all.PEP...
gff_to_contig_parent_to_cds_hash: saving all from ./Repo_spec.txt.all.GFF3...

15408 / 37490 found (GFF ./Repo_spec.txt.all.GFF3 entries in FASTA ./Repo_spec.txt.all.PEP)
15408 / 37490 found (FASTA ./Repo_spec.txt.all.PEP entries in GFF ./Repo_spec.txt.all.GFF3)
WARNING: ./Repo_spec.txt.all.PEP and ./Repo_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match. Use -v for further info.
fasta_to_struct: saving from ./Repo_spec.txt.all.CDS...
gff_to_contig_parent_to_cds_hash: saving all from ./Repo_spec.txt.all.GFF3...

15408 / 37490 found (GFF ./Repo_spec.txt.all.GFF3 entries in FASTA ./Repo_spec.txt.all.CDS)
15408 / 37490 found (FASTA ./Repo_spec.txt.all.CDS entries in GFF ./Repo_spec.txt.all.GFF3)
WARNING: ./Repo_spec.txt.all.CDS and ./Repo_spec.txt.all.GFF3 repository sequence databases are not correctly formatted. Change settings and re-run, or rename ID's in FASTA or GFF to match. Use -v for further info.
../util/Create_full_repo_sequence_databases.pl: finished check. `

**Comment by rhysf** [comment]
Hiya. Yes, gff is a very flexible format, so there is no easy way I’ve been able to choose to match id’s in the fasta files and the vcfs without making assumptions that may be incorrect.

you may be able to tweak the parameters for it to match. Alternatively, you might be able to open your files in a text editor and make changes to ensure they match, such as remove all ‘gene-‘ from gff ids. Otherwise, you may need some basic scripting to deal with this. Good luck and let me know if you have further issues once resolved.
