### ISSUE TITLE
Orthologs summary

### ISSUE THREAD

**Issue by rogergsilva** [rhysf/Synima#42]
Hi Rhys!

I hope this message finds you well!

I was running Synima when I hit an error message. I hope you could help me figuring out what is going on.

`
perl ../util/Create_full_repo_sequence_databases.pl -r ./my_spec.txt
perl ../util/Blast_grid_all_vs_all.pl -r ./my_spec.txt
perl ../util/Blast_all_vs_all_repo_to_RBH.pl -r ./my_spec.txt
`

Everything had run perfectly, until the next command line.

`
perl ../util/Orthologs_to_summary.pl -o ./RBH_outdir/PEP.RBH.OrthoClusters -t RBH
ERROR: ./Repo_spec.txt.all.PEP not recognised as a file : No such file or directory
`

List of files in the RBH_outdir:
-rw-r--r-- 1 roger roger 1627482 Apr 17 19:26 PEP.RBH
-rw-r--r-- 1 roger roger 2110530 Apr 17 19:26 PEP.RBH.OrthoClusters
-rw-r--r-- 1 roger roger  332850 Apr 17 19:26 PEP.RBH.pairs
-rw-r--r-- 1 roger roger  232689 Apr 17 19:26 PEP.RBH.slclust

The PEP.RBH.OrthoClusters file is in the mentioned folder and it looks perfect. Could you give me an idea of what I am doing wrong?

Thank you so much,

**Comment by rhysf** [comment]
Hi, I think the error message is fairly self explanatory. 

Orthologs_to_summary.pl is looking for your Repo_spec.txt.all.PEP file, and the default location it is looking in is ./Repo_spec.txt.all.PEP

Given you've named your repo 'my_spect.txt' then the file it needs is probably called 'my_spect.txt.all.PEP' instead - so you need to change the default parameter specifying the file name/location.

**Comment by rogergsilva** [comment]
https://github.com/rhysf/Synima/issues/41

I found this thread and I think that would be the same issue now.

I'll look at it. Thank you.
