### ISSUE TITLE
synteny plot (circos) for genes

### ISSUE THREAD

**Issue by daniazi** [rhysf/Synima#8]
Hi Rhys, how can I obtain alignment data for genes to visualize gene synteny in Circos plot. The R script in the package produces linear synteny plot using same kind of data.  Is there a way to extract feature-specific coordinates for e.g, genes from Synima output files which can be used for Circos plotting?

**Comment by rhysf** [comment]
Dear Adnan,

If you are interested in updating the output of the Synima plot, then there
are a variety of parameters that you should be able to specify in the
config file or on the command line on the first run.

However, synima does not produce data intended for use with circos. It is
entirely possible that the Synima ortholog prediction pipeline produces
data that could be used with circos, but this is something the authors of
circos would need to assist with.

Best,
Rhys
