### ISSUE TITLE
error while running examples

### ISSUE THREAD

**Issue by ivanaKraiselburd** [rhysf/Synima#9]
I cannot make the examples work according to the Full example pipeline. I get the following:

$perl ../util/Blast_grid_all_vs_all.pl -r ./Repo_spec.txt
fasta_id_to_seq_hash: saving sequences from ./Repo_spec.txt.all.PEP...
Splitting seq dictionary for blasting...
CNB2 = ./CNB2/CNB2_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP...
Cryp_gatt_IND107_V2 = ./Cryp_gatt_IND107_V2/Cryp_gatt_IND107_V2_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP...
Cryp_gatt_CA1280_V1 = ./Cryp_gatt_CA1280_V1/Cryp_gatt_CA1280_V1_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP...
CNB_WM276_v2 = ./CNB_WM276_v2/CNB_WM276_v2_Final_CUSTOMCALLGENES_1.annotation.pep.synima-parsed.PEP...
CMD: formatdb -i ./Cryp_gatt_IND107_V2/Cryp_gatt_IND107_V2_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -p T
Error, cmd formatdb -i ./Cryp_gatt_IND107_V2/Cryp_gatt_IND107_V2_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP -p T died with return -1

Could you tell me what might be the problem? 

Thanks

**Comment by rhysf** [comment]
Hi @ivanaKraiselburd 

That error comes from not having blast in your path. Make sure a local copy of legacy blast is installed in your computer, and use the command PATH=$PATH:/location/of/blast before using that script.
